### ISSUE TITLE
Error when you stay in an input

### ISSUE THREAD

**Issue by mcunha98** [m-thalmann/overlayjs#1]
I did the simple test, show the overlayjs and focus to an input, when I hit any key the popup stay visible, that I must to click out the area to close and back to the input.

![image](https://user-images.githubusercontent.com/6831010/47260301-684ba580-d48f-11e8-9b2a-625142482038.png)

**Comment by mcunha98** [comment]
Here a simple test that I did using your sample page:

https://jsfiddle.net/4barc985/

**Comment by m-thalmann** [comment]
I don't see any problem here
